apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-intermediary
  labels:
    app: broker-intermediary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: broker-intermediary
  template:
    metadata:
      labels:
        app: broker-intermediary
    spec:
      containers:
        - name: broker-intermediary
          image: northamerica-northeast1-docker.pkg.dev/kubernetes-sistemas-distribui/identidaddigital/broker-intermediary:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "1000Mi"
              cpu: "2000m"
            requests:
              memory: "128Mi"
              cpu: "256m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: broker-intermediary
  name: broker-intermediary #
  namespace: default
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: broker-intermediary #
  type: LoadBalancer