spring:
  application:
    name: "api-gateway"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "api-gateway"
    description: "Digital Identity Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    com:
      digital-identity-api:
        api-gateway: DEBUG


