server:
  port: 8081
spring:
  application:
    name: "broker-intermediary"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3306/citizensdb
    username: root
    password: root
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
  rabbitmq:
#    host: localhost
    host: 35.239.132.181
    port: 5672
    username: sistemasdistribuidos
    password: sistemasdistribuidos
#    username: guest
#    password: guest
    queues:
      citizen: "citizen"
      citizenSubscription: "citizenSubscription"
      digitalIdentityServices: "digitalIdentityServices"
      document: "document"
      externalCompany: "externalCompany"
      offeredSolution: "offeredSolution"
      transfers: "transfers"
      registerCitizen: "registerCitizen"
      notificationQueue: "notificationQueue"
