server:
  port: 8080
spring:
  application:
    name: "citizen"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://34.136.134.246:3306/citizensdb
#    url: jdbc:mysql://localhost:3306/citizensdb
    username: sistemasdistribuidos
#    username: root
    password: sistemasdistribuidos
#    password: root
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
  rabbitmq:
    host: 35.239.132.181
#    host: localhost
    port: 5672
    username: sistemasdistribuidos
    password: sistemasdistribuidos
#    username: guest
#    password: guest
    queues:
      citizen: "citizen"
      citizenSubscription: "citizenSubscription"
      digitalIdentityServices: "digitalIdentityServices"
      document: "document"
      externalCompany: "externalCompany"
      offeredSolution: "offeredSolution"
      transfers: "transfers"
logging:
  level:
    org:
      springframework:
        web: DEBUG
        boot:
          autoconfigure: DEBUG
