server:
  port: 8080
spring:
  application:
    name: "citizen"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3306/citizensdb
    username: root
    password: root
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queues:
      citizen: "citizen"
      citizenSubscription: "citizenSubscription"
      digitalIdentityServices: "digitalIdentityServices"
      document: "document"
      externalCompany: "externalCompany"
      offeredSolution: "offeredSolution"
      transfers: "transfers"
