server:
  port: 8081
spring:
  application:
    name: "citizen"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://34.136.134.246:3306/citizensdb
    username: sistemasdistribuidos
    password: sistemasdistribuidos
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
  rabbitmq:
    host: 35.239.132.181
    port: 5672
    username: sistemasdistribuidos
    password: sistemasdistribuidos
    queues:
      citizen: "citizen"
      citizenSubscription: "citizenSubscription"
      digitalIdentityServices: "digitalIdentityServices"
      document: "document"
      externalCompany: "externalCompany"
      offeredSolution: "offeredSolution"
      transfers: "transfers"
