apiVersion: apps/v1
kind: Deployment
metadata:
  name: document
  labels:
    app: document
spec:
  replicas: 2
  selector:
    matchLabels:
      app: document
  template:
    metadata:
      labels:
        app: document
    spec:
      containers:
        - name: documents
          image: northamerica-northeast1-docker.pkg.dev/kubernetes-sistemas-distribui/identidaddigital/document:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "1000Mi"
              cpu: "1000m"
            requests:
              memory: "128Mi"
              cpu: "256m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: document
  name: document #
  namespace: default
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: document #
  type: LoadBalancer