name: Deploy to GKE
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    # Configura gcloud y autentica
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    
    # Construye y sube las imágenes Docker
    - name: Build and Push Docker images
      run: ./deploy/build-and-push.sh
    
    # Despliega a Kubernetes
    - name: Deploy to Kubernetes
      run: ./deploy/deploy-to-k8s.sh
