name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B install --file pom.xml

  test:
    needs: build
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - run: mvn -B test --no-transfer-progress --file pom.xml
      - uses: actions/upload-artifact@v2
        with:
            name: jacoco-reports
            path: target/site/jacoco

  codeQuality:
    needs: build
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - run: mvn -B detekt:check --no-transfer-progress -Ddetekt.baseline=baseline-cicdapp-dvj.xml --file pom.xml
